spring:
  application:
    name: auth-service

  # database connection details..
  datasource:
    url: jdbc:postgresql://localhost:5432/tncdb?options=-c%20TimeZone=UTC
    username: admin
    password: admin

  jpa:
    hibernate:
      ddl-auto: update # This tells hiberate to create/update table automatically. [NOT to be used in production / For dev only]
      dialect: org.hibernate.dialect.PostgreSQLDialect # fix: timezone mis-matched issue with postgres -> this makes sure it connects.
    properties:
      hibernate.jdbc.time_zone: UTC

    show-sql: true # This prints sql queries in log.

server:
  port: 8082
