version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: tnc-postgres
    environment:
      POSTGRES_DB: tncdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data     # this persist the database, even if the container goes down !

  # redis:
  #   image: redis:7
  #   container_name: tnc-redis
  #   ports:
  #     - "6379:6379"

  # zookeeper:
  #   image: confluentinc/cp-zookeeper:7.5.0
  #   container_name: tnc-zookeeper
  #   environment:
  #     ZOOKEEPER_CLIENT_PORT: 2181

  # kafka:
  #   image: confluentinc/cp-kafka:7.5.0
  #   container_name: tnc-kafka
  #   depends_on:
  #     - zookeeper
  #   ports:
  #     - "9092:9092"
  #   environment:
  #     KAFKA_BROKER_ID: 1
  #     KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  #     KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
  #     KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

# Define the named volumes here at the bottom of the file  
volumes:
  postgres-data: