spring:
  application:
    name: api-gateway # Identifies this microservice in logs and discovery
  
  cloud:
    gateway:
      routes:
        # Route configurations for downstream services
        - id: analysis-service
          uri: http://localhost:8081  # The local destination port for this backend
          predicates:
            - Path=/analyses/**  # Any endpoint starting with /analyses routing goes here
          filters:
            - JwtAuthenticationFilter  # custom JWT auth check for the routed url.

server:
  port: 8080  # Public entry point for users/frontend clients
